src/main.cpp File Reference
implements a main function to check the behavior of the parray template and docs hierarchy.
#include <iostream>
*
#include <list>
*
#include `Document.h`
*
#include `PointerArray.cpp`
*
Functions
void logTest (std::string msg)
function used to highlights debugging logs by printing a frame of '#'.
int main ()
the main function to check project consistency by console logging.
Variables
const std::string LOG_HEADER = ` Main: `
the debugging string to be appended on log head by this manager
const std::string LOG_HEADER_TEST = `\t[TEST] ` + LOG_HEADER
the debugging string to be appended on log head by the StringPointerArray::tester()
Detailed Description
implements a main function to check the behavior of the parray template and docs hierarchy.
Author
Buoncompagni Luca
Date
Sep 17, 2016
See Also
StringPointerArray
plist
Document
SpreadSheet
WebPage
docs
Definition in file main.cpp.
Function Documentation
int main ()
the main function to check project consistency by console logging.
check the behavior of the template implementation (parray) through the parray::StringPointerArray::tester() function.
check the behavior of the Document hierarchy (docs).
define a document with given title and keywords.
define another document with given title and keywords.
make a copy of the second Document, augment title and change keywords.
create a copy of the third Document. Overwrite the title and remove keywords.
create a Document with a given set of keywords.
create a WebPage. Add keywords and contents.
make a new Web Page by specifying only the title and url.
make a new Web Page by specifying the title, the url, the contents and keywords.
make a copy of the second WebPage. Augment the title, remove a keyword and add a contents.
Make a copy of the third WebPage. Set a new title and clear keywords.
create a new WebPage with a given keywords set.
create a new WebPage with a given keywords and contents sets. Set also its title.
create a new default Spreadsheet.
create a new Spreadsheet with given number of columns and rows.
create a new Spreadsheet with a given key words set, a title, the number of row and columns.
create a new SpreadSheet as the copy of the previous and set the title.
put all the created Document in a list and print its contents.
Definition at line 39 of file main.cpp.
References parray::StringPointerArray::add(), docs::WebPage::getContents(), docs::Document::getKeyWords(), docs::Document::getTitle(), LOG_HEADER_TEST, logTest(), parray::PointerArray< T >::pack(), parray::PointerArray< T >::remove(), parray::PointerArray< T >::resize(), docs::Spreadsheet::setColoumnCnt(), docs::WebPage::setContents(), parray::PointerArray< T >::setSize(), docs::Document::setTitle(), and parray::StringPointerArray::tester().