docs Namespace Reference
This namespace is used to collect all the document hierarchy classes and types.
Classes
class DocType
The class containing the definition of Document Types names.
class Document
This is the base class of the Document hierarchy.
class WebPage
It describes a web page as a Document extensions.
class Spreadsheet
This describes a spreadsheet as a Document extension.
Enumerations
enum Type { DOCUMENT,
WEB_PAGE,
SPREADSHEET
 }
Instances of document identifier values.
Functions
std::ostream & operator<< (std::ostream &strm, const Document &doc)
bool operator== (const Document &c1, const Document &c2)
bool operator!= (const Document &c1, const Document &c2)
Variables
const std::string DEFAULT_DOCUMENT_TITLE = `Default Title`
The title, if not specified on Document construction.
const int DEFAULT_DOCUMENT_KWSIZE = 3
The size, of key words if not specified on Document construction.
const std::string DEFAULT_WEBPAGE_URL = `www.defualt.com`
The url, if not specified on WebPage construction.
const int DEFAULT_WEBPAGE_TEXTSIZE = 10
The size of contents, if not specified on WebPage construction.
const int DEFAULT_SPREADSHEET_COLCNT = 7
The number of columns, if not specified on Spreadsheet construction.
const int DEFAULT_SPREADSHEET_ROWCNT = 2
The number of rows, if not specified on Spreadsheet construction.
const std::string TYPE_NAME_DOCUMENT = `\`Document\``
The name of the Type.DOCUMENT type values.
const std::string TYPE_NAME_WEBPAGE = `\`Web Page\``
The name of the Type.WEB_PAGE type values.
const std::string TYPE_NAME_SPREADSHEET = `\`Spreadsheet\``
The name of the Type.SPREADSHEET type values.
const std::string LOG_HEADER = ` DocumenHierarchy: `
the debugging string to be appended on log head by this Document
const std::string LOG_HEADER_TEST = `\t[TEST] ` + LOG_HEADER
the debugging string to be appended on log head by the StringPointerArray::tester() for Test logs
const std::string LOG_HEADER_WARNING = `[WARNING] ` + LOG_HEADER
the debugging string to be appended on log head by the StringPointerArray::tester() for Warning logs
const std::string LOG_HEADER_INFO = `[INFO] ` + LOG_HEADER
the debugging string to be appended on log head by the StringPointerArray::tester() for Info logs
const std::string LOG_HEADER_ERROR = `[ERROR] ` + LOG_HEADER
the debugging string to be appended on log head by the StringPointerArray::tester() for Error logs
Detailed Description
This namespace is used to collect all the document hierarchy classes and types.
Enumeration Type Documentation
enum docs::Type
Instances of document identifier values.
Enumerator
DOCUMENT
 only Document objects will have this Document::getType() value
WEB_PAGE
 only WebPage objects will have this Document::getType() value
SPREADSHEET
 only Spreadsheet objects will have this Document::getType() value
Definition at line 68 of file Document.h.
Function Documentation
bool docs::operator!= (const Document & c1, const Document & c2)
it returns '!c1.equals(c2)'. This method should not be implemented on derived classes.
Definition at line 88 of file Document.cpp.
References operator==().
std::ostream& docs::operator<< (std::ostream & strm, const Document & doc)
it returns 'strm << doc.toString()'. This method should not be implemented on derived classes.
Definition at line 61 of file Document.cpp.
References docs::Document::toString().
bool docs::operator== (const Document & c1, const Document & c2)
it returns 'c1.equals(c2)'. This method should not be implemented on derived classes.
Definition at line 84 of file Document.cpp.
References docs::Document::equals().
Referenced by operator!=().